
#### Cadastrar medico
POST http://localhost:5098/hospital/cadastrar/medico
Content-Type: application/json

{
    "nome" : "Teste Médico2",
    "genero" : "Masculino",
    "especialidade" : "Cirurgião",
    "crm" : 634456,
    "telefone" : "4002-8922",
    "descricao" : "Doutor",
    "setorId" : "82be34b3-87ae-46d9-91f0-de7ee7d6a9d9"
}

#### Buscar medico
GET http://localhost:5098/hospital/buscar/medico/d3214239-f19d-4002-9c33-6a6b09272827
#### Listar medico
GET http://localhost:5098/hospital/listar/medico

#### Alterar medico
PUT http://localhost:5098/hospital/atualizar/medico/d3214239-f19d-4002-9c33-6a6b09272827
Content-Type: application/json

{
    "nome" : "André",
    "genero" : "Masculino",
    "especialidade" : "Enfermeiro",
    "crm" : 987654321,
    "telefone" : "4002-0202",
    "descricao" : "Enfermeiro",
    "setorid" : "Raio-X"
}

#### Deletar medico
DELETE http://localhost:5098/hospital/deletar/medico/d3214239-f19d-4002-9c33-6a6b09272827