
#### Cadastrar paciente
POST http://localhost:5098/hospital/cadastrar/paciente
Content-Type: application/json

{
    "nome" : "Lázaro",
    "cpf" : "1000043",
    "genero" : "Masculino",
    "telefone" : "4002-8456",
    "descricao" : "Sintomas de tuberculose"
    
}

#### Buscar paciente
GET http://localhost:5098/hospital/buscar/paciente/92f500bb-cf99-4241-8ed5-620f6782a7e1
#### Listar paciente
GET http://localhost:5098/hospital/listar/paciente

#### Alterar paciente
PUT http://localhost:5098/hospital/alterar/paciente/92f500bb-cf99-4241-8ed5-620f6782a7e1
Content-Type: application/json

{
    "nome" : "Beatriz da Costa",
    "cpf" : "100003450-77",
    "genero" : "Feminino",
    "telefone" : "4002-8456",
    "descricao" : "Fadiga"
    
}

#### Deletar paciente
DELETE http://localhost:5098/hospital/deletar/paciente/92f500bb-cf99-4241-8ed5-620f6782a7e1
