
#### Cadastrar setor
POST http://localhost:5098/hospital/cadastrar/setor
Content-Type: application/json

{
    "nome" : "Teste"
}

#### Buscar setor
GET http://localhost:5098/hospital/buscar/setor/214697d8-2ce2-4777-ab8c-180fe9b7c8cd

#### Listar setor
GET http://localhost:5098/hospital/listar/setor

#### Alterar setor 
PUT http://localhost:5098/hospital/atualizar/setor/214697d8-2ce2-4777-ab8c-180fe9b7c8cd
Content-Type: application/json

{
    "nome" : ""
}

#### Deletar setor
DELETE http://localhost:5098/hospital/deletar/setor/214697d8-2ce2-4777-ab8c-180fe9b7c8cd