
#### Cadastrar setor
POST http://localhost:5098/hospital/cadastrar/setor
Content-Type: application/json

{
    "nome" : "Teste"
}

#### Buscar setor
GET http://localhost:5098/hospital/buscar/setor/64c81527-6d3c-4cba-82c5-7b2a6893b4e8

#### Listar setor
GET http://localhost:5098/hospital/listar/setor

#### Alterar setor 
PUT http://localhost:5098/hospital/atualizar/setor/67237d87-afae-486f-9df2-384d2b88577f
Content-Type: application/json

{
    "nome" : "TESTE2"
}

#### Deletar setor
DELETE http://localhost:5098/hospital/deletar/setor/67237d87-afae-486f-9df2-384d2b88577f